[features]
seeds = false
[programs.devnet]
mysolproject = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/celestinorazatos/.config/solana/id.json"

[scripts]
test = "node tests/mysolproject.js"
